name: Github Actions demo
on: 
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name : compare values
        shell: bash
        run: |
          echo "This is the working directory"
          echo "var=10" >> $GITHUB_ENV
          ls
          pwd
      - name : print
        if: env.var == 10
        run:  echo "ghjdfhgg"
          #if [ $var -lt 70 ]
          #then
           # uses: actions/github-script@v3
            #with:
             # script: |
              #  core.setFailed('coverage less than 70')
          #fi
