name: Github Actions demo
on: 
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name : compare values
        shell: bash
        run: |
          pwd
          ls
          echo "This is the working directory"
          #var = 10
          if [ $var -lt 70 ]
          then
            uses: actions/github-script@v3
            with:
              script: |
                core.setFailed('coverage less than 70')
          fi
