name: Github Actions demo
on: 
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name : compare values
        run: |
          var = 10
          if: ${{ var }} < 0.7
          uses: actions/github-script@v3
          with:
             script: |
                core.setFailed('coverage less than 70')
