name: Github Actions demo
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2 
      - name : compare values
        shell: bash
        run: |
          echo "This is the working directory"
          a=$(egrep -o 'line-rate="[^"]+"' coverage.cobertura.xml | cut -d\" -f2)
          b=$(echo "$a*100" | bc)
          echo "The coverage is $b%"
          echo "var=$a" >> $GITHUB_ENV
          ls
          pwd
      - name : print
        if: env.var < 0.8
        uses: actions/github-script@v3
        with:
          script: |
             core.setFailed('coverage less than 70%')
      - name: Check if this will run after above step fails 
        run:  echo "The test passed"
          #if [ $var -lt 70 ]
          #then
           # uses: actions/github-script@v3
            #with:
             # script: |
              #  core.setFailed('coverage less than 70')
          #fi
