name: Github Actions demo
on: 
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2 
      - name : compare values
        shell: bash
        run: |
          echo "This is the working directory"
          a=$(egrep -o 'line-rate="[^"]+"' coverage.cobertura.xml | cut -d\" -f2)
          #echo $a
          echo "var=$a*100" >> $GITHUB_ENV
          ls
          pwd
      - name : print
        if: env.var <= 10
        run:  echo "${{ env.var }}"
          #if [ $var -lt 70 ]
          #then
           # uses: actions/github-script@v3
            #with:
             # script: |
              #  core.setFailed('coverage less than 70')
          #fi
